### PR TITLE
Add a tip for how to remember the `ysiw` command

### PR DESCRIPTION
**Pull request by dwmkerr**
See: https://github.com/tpope/vim-surround/issues/128

It took me a little bit of googling to understand why the command was `ysiw`, this little tip on the README might make it easier for novices like myself to understand what is going on (and remember the command!).

### CODE REVIEW

**Comment by benoittgt** [comment]
`y	yank into register` 
and 
`i	inner`
So it should be
_"yank-surround-inner-word"_

**Comment by dwmkerr** [comment]
Hi @benoittgt, in the docs it's:

image

Suggesting the mnemonic can be remembered with `you surround`, I don't think the `y` relates to yank in this case (see #138) but I might be wrong!

**Comment by benoittgt** [comment]
Yes you are correct for the yank. It's `y	y	yank into register (does not change the text)` (from motions.txt)

**Comment by zgpio** [comment]
Is `y` referring to `yield` better?

**Comment by tpope** [comment]
Here's the real mnemonic: `d`, `c`, and `y` are the three most important Vim operations, and `ds`, `cs`, and `ys` are the three most important Surround operations.

**Pull request closed without merging**
